### ISSUE TITLE
Failed to create VM importer unexpected EOF on health check

### ISSUE THREAD

**Issue by strammell-incomm** [VictoriaMetrics/vmctl#16]
I just set up a VictoriaMetrics simple cluster: 2 insert nodes behind a load balancer, 2 select nodes behind a load balancer, and 2 storage nodes. I am able to remote write to it just fine with our cur Prometheus server. When trying to do vmcctl from the Prometheus server with a snapshot to the vminsert load balancer endpoint I get a: 

`failed to create VM importer: ping to "https://remore-fqdn:8480" failed: Get "https://remote-fqdn:8480/health": unexpected EOF`

When I do a curl to https://remote-fqdn:8480/health I get the expected OK. Here is what my insert command looks like:

`./vmctl prometheus --prom-snapshot /opt/prometheus-data/snapshots/20200512T211728Z-7b43c0d7bc688062/ --vm-addr https://remote-fqdn:8480 --vm-account-id 0`

Am I missing something? Does this need to go to the vmselect endpoint (seems weird to me)? Any help would be appreciated.

**Comment by hagen1778** [comment]
Hi @strammell-incomm! 

> Does this need to go to the vmselect endpoint (seems weird to me)?

No, the add must be vminsert.

Can you rule out balancer somehow? I wondering if balancer sends truncated response or broken Content-Length.... Would be cool to get `curl -v https://remote-fqdn:8480/health` output.

**Comment by strammell-incomm** [comment]
I think you might be right. May have to open up another firewall lol. Here is the output:

* About to connect() to remote-fqdn port 8480 (#0)
*   Trying 192.168.1.26...
* Connected to remote-fqdn (192.168.1.26) port 8480 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=*.fqdn,O="Interactive Communications International, Inc.",L=Atlanta,ST=Georgia,C=US
*       start date: Feb 13 15:55:39 2020 GMT
*       expire date: Feb 13 16:25:37 2022 GMT
*       common name: *.fqdn
*       issuer: CN=Entrust Certification Authority - L1K,OU="(c) 2012 Entrust, Inc. - for authorized use only",OU=See www.entrust.net/legal-terms,O="Entrust, Inc.",C=US
> GET /health HTTP/1.1
> User-Agent: curl/7.29.0
> Host: remote-fqdn:8480
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Wed, 13 May 2020 21:41:33 GMT
< Content-Length: 2
<
* Connection #0 to host remote-fqdn left intact

**Comment by strammell-incomm** [comment]
Well, we can close this one. @hagen1778 you were on the right path. I switched the load balancer (traefik) from a https/tcp entry to just HTTP all the way through and it works like a charm now. Well, I'm getting a new error but that's on my end.

**Comment by pavdmyt** [comment]
Had similar issue trying to import prometheus data into VictoriaMetrics, receiving following error:

```
2020/05/21 18:48:24 failed to create VM importer: ping to "https://our.victoriametrics.com" failed: bad status code: 404
```

We're running cluster VictoriaMetrics in K8s, exposing `vminsert` endpoints via nginx-ingress. The problem was fixed after exposing `/health` endpoint at ingress.

It should be probably mentioned somewhere in docs that `vmctl` checks insert endpoints availability by fetching `/health`.

**Comment by hagen1778** [comment]
Thanks @pavdmyt! Mentioned this in https://github.com/VictoriaMetrics/vmctl/commit/44ba23f76a13dc583a2f39273a9f7aef0166df21.
