### ISSUE TITLE
[Feature Request] add vmctl binary

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/vmctl#20]
Hello!
Thanks for VictoriaMetrics!
druchoo create issue for vmctl rpm packages.
https://github.com/patsevanton/victoriametrics-rpm/issues/2

Please create/add vmctl binary.

**Comment by hagen1778** [comment]
Hi! See latest release https://github.com/VictoriaMetrics/vmctl/releases/tag/0.1.0

**Comment by patsevanton** [comment]
Thanks!
