### ISSUE TITLE
Error importing data from InfluxDB

### ISSUE THREAD

**Issue by Ejant** [VictoriaMetrics/vmctl#30]
Hi all!

I'm trying to import my historic Prometheus database (InfluxDB 1.8.0) to VictoriaMetrics:

vmctl version:

root@XXXXXXXXXX:/opt#  ./vmctl-linux-amd64 --version
vmctl version 0.3.0, rev. 4217ae5a09c1c70847e58d3ac631966afd1b19e7, built at 2020-10-14_10:54:18

Importing:

 ./vmctl-linux-amd64 influx --influx-addr http://1.2.3.4:8086 --influx-user admin --influx-password XxXxX --influx-database prometheus
InfluxDB import mode
2020/11/16 20:28:47 Exploring scheme for database "prometheus"
2020/11/16 20:28:47 fetching fields: command: "show field keys"; database: "prometheus"; retention: "autogen"
2020/11/16 20:28:48 found 1000 fields
2020/11/16 20:28:48 fetching series: command: "show series"; database: "prometheus"; retention: "autogen"
2020/11/16 20:29:07 found 2106087 series
**2020/11/16 20:29:08 explore query failed: can't find field keys for measurement "jvm_gc_collection_seconds_count"**

Info about jvm_gc_collection_seconds_count

```
> use prometheus;
Using database prometheus
> select * from jvm_gc_collection_seconds_count limit 10;
name: jvm_gc_collection_seconds_count
time                __name__                        gc                  instance   job       monitor value
----                --------                        --                  --------   ---       ------- -----
1577750404513000000 jvm_gc_collection_seconds_count ConcurrentMarkSweep XXXXXX-3  cassandra example 211188
1577750404513000000 jvm_gc_collection_seconds_count ParNew              XXXXXX-3  cassandra example 16341106
1577750410520000000 jvm_gc_collection_seconds_count ConcurrentMarkSweep XXXXXX-2  cassandra example 159725
1577750410520000000 jvm_gc_collection_seconds_count ParNew              XXXXXX-2  cassandra example 15038508
1577750416120000000 jvm_gc_collection_seconds_count ConcurrentMarkSweep XXXXXX-7  cassandra example 167201
1577750416120000000 jvm_gc_collection_seconds_count ParNew              XXXXXX-7  cassandra example 17843084
1577750416810000000 jvm_gc_collection_seconds_count ConcurrentMarkSweep XXXXXX-10 cassandra example 184970
1577750416810000000 jvm_gc_collection_seconds_count ParNew              XXXXXX-10 cassandra example 18190132
1577750430441000000 jvm_gc_collection_seconds_count ConcurrentMarkSweep XXXXXX-8  cassandra example 182340
1577750430441000000 jvm_gc_collection_seconds_count ParNew              XXXXXX-8  cassandra example 17290695



show field keys from jvm_gc_collection_seconds_count;
name: jvm_gc_collection_seconds_count

fieldKey fieldType
-------- ---------
value    float


```
Am I missing something? 
Thanks!

**Comment by hagen1778** [comment]
Hi @Ejant! Thanks for report!
Could you pls show what `show series from jvm_gc_collection_seconds_count;` shows?

**Comment by Ejant** [comment]
Hi! Sorry, i forgot that...

> show series from jvm_gc_collection_seconds_count limit 10;
key
---
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-A01-A:7070,job=cowifi-cassandra
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-A01-A:7070,job=cowifi-cassandra,monitor=example
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-02-A:7070,job=cowifi-cassandra
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-02-A:7070,job=cowifi-cassandra,monitor=example
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST03-A:7070,job=cowifi-cassandra
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-03-A:7070,job=cowifi-cassandra,monitor=example
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-a04-A:7070,job=cowifi-cassandra
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-A04-A:7070,job=cowifi-cassandra,monitor=example
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-A05-A:7070,job=cowifi-cassandra
jvm_gc_collection_seconds_count,__name__=jvm_gc_collection_seconds_count,gc=ConcurrentMarkSweep,instance=SOME-HOST-06-A:7070,job=cowifi-cassandra


FYI:
This InfluxDB instance is a remote write of Prometheus, I'm trying to import old data and replace it with VictoriaMetrics. Maybe it can help.

Keep up the good work!

**Comment by hagen1778** [comment]
Thanks for the info! Unfortunately, I can't find any issues so far. I also tried to setup Prometheus+InfluxDB (remote write) and then migrate metrics from inlfux - works well. I suppose there is some corner case I can't foresee. Have you tried to apply filters in order to understand if it is only some specific series affected? For example, you can try to filter series via following flag `--influx-filter-series "on prometheus from jvm_gc_collection_seconds_count where job ='cowifi-cassandra"`. 
I'd also appreciate if you can share influxDB dump sample for reproducing the issue. If this is an option pls send it to `info@victoriametrics.com`.

**Comment by Ejant** [comment]
/opt# ./vmctl-linux-amd64 influx --influx-addr http://192.168.15.176:8086 --influx-user admin --influx-password Pmqfqha --influx-database prometheus --influx-filter-series "on prometheus from jvm_gc_collection_seconds_count where job ='cowifi-cassandra'"
InfluxDB import mode
2020/11/21 16:43:47 Exploring scheme for database "prometheus"
2020/11/21 16:43:47 fetching fields: command: "show field keys"; database: "prometheus"; retention: "autogen"
2020/11/21 16:43:47 found 1000 fields
2020/11/21 16:43:47 fetching series: command: "show series on prometheus from jvm_gc_collection_seconds_count where job ='cowifi-cassandra'"; database: "prometheus"; retention: "autogen"
2020/11/21 16:43:48 found 20 series
2020/11/21 16:43:48 explore query failed: can't find field keys for measurement "jvm_gc_collection_seconds_count"

I'm sending dump to email

Kr.

**Comment by Ejant** [comment]
I've found that 
max-row-limit parameter under [http] in my influxdb.conf was the problem.

Thanks a lot!!!

**Comment by hagen1778** [comment]
Glad to here! I'll try to improve docs in order to list possible causes of the error. Thanks!

**Comment by hagen1778** [comment]
Updated docs in commit https://github.com/VictoriaMetrics/vmctl/commit/072abc3d6a0acff2607e0d61332630e32e44de9a
