### ISSUE TITLE
Error importing from InfluxDB 

### ISSUE THREAD

**Issue by Ejant** [VictoriaMetrics/vmctl#31]
Hi all!!!

I'm getting problems importing metrics from influxdb:

root@GRFMONLBBE002:/opt# ./vmctl-linux-amd64 influx --influx-addr http://x.x.x.x:8086 --vm-addr http://y.y.y.y:8428 --influx-user admin --influx-password Pmqfqha --influx-database prometheus --influx-filter-series "where job='dell_s4810' and instance='z.z.z.z' "
InfluxDB import mode
2020/12/14 11:26:08 Exploring scheme for database "prometheus"
2020/12/14 11:26:08 fetching fields: command: "show field keys"; database: "prometheus"; retention: "autogen"
2020/12/14 11:26:09 found 3447 fields
2020/12/14 11:26:09 fetching series: command: "show series where job='dell_s4810' and instance='x.x.x.x' "; database: "prometheus"; retention: "autogen"
2020/12/14 11:26:09 found 5713 series
Found 5713 timeseries to import. Continue? [Y/n] y
2020/12/14 11:26:11 influx error: request failed for "ifAlias"."value": response error for select "value" from "ifAlias" where "__name__"='ifAlias' and "ifAlias"='' and "ifDescr"='Loopback 2' and "instance"='z.z.z.z' and "job"='dell_s4810': error parsing query: **found BADSTRING, expected identifier, string, number, bool at line 1, char 71**

Influx query:

>  select "value" from "ifAlias" where "__name__"='ifAlias' and "ifAlias"='' and "ifDescr"='Loopback 2' and "instance"='z.z.z.z' and "job"='dell_s4810'
>

if you need something elese just let me know

Kr.

**Comment by hagen1778** [comment]
Hi @Ejant! Thanks for report!
Have you tried to execute this request manually via influx client? The error message says that error is at position `"ifAlias"=''`.
I wonder if tag value for it was properly parsed...

**Comment by Ejant** [comment]
Hey Roman, indeed, there was a problem on that metric. A Dell switch was sending one ifAlias='NULL 0'. I've dropped that metric and it worked.
Thanks!! I'm closing this
