### ISSUE TITLE
Add ability to set extra labels during data import

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/vmctl#34]
# The issue

Sometimes it is needed to move time series from some data source to VictoriaMetrics while adding extra labels to all the imported time series.

# The solution
VictoriaMetrics and [vmagent](https://victoriametrics.github.io/vmagent.html) support `extra_label` query args during data ingestion over HTTP-based data ingestion protocols. See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1007 for details. It would be great if `vmctl` would support `-extra_label` command-line flag and pass it to `extra_label` query arg during data import for all the supported data sources.

# The workaround

It is possible to add extra labels via relabeling. See [this article](https://medium.com/@romanhavronenko/victoriametrics-how-to-migrate-data-from-prometheus-filtering-and-modifying-time-series-6d40cea4bf21) for details. But this is more complex and more error-prone approach comparing to the solution described above.

**Comment by hagen1778** [comment]
@valyala the feature was added in https://github.com/VictoriaMetrics/vmctl/releases/tag/0.4.0

**Comment by valyala** [comment]
Then closing the feature request as done.
