### ISSUE TITLE
Labels management

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/vmctl#4]
There should be a way how to remove or add extra labels to timeseries before import.

**Comment by johnseekins** [comment]
Is this covered by the relabel_config work that was done in VictoriaMetrics proper?

**Comment by hagen1778** [comment]
Hi @johnseekins! Looks like you're right! I need to verify this and update docs accordingly. Thanks!

**Comment by hagen1778** [comment]
Labels management can be achieved by `relabel_config` on VM side. Pls see the following article for details https://medium.com/@romanhavronenko/victoriametrics-how-to-migrate-data-from-prometheus-filtering-and-modifying-time-series-6d40cea4bf21
