### ISSUE TITLE
Influx mode: support for Prometheus data written via remote_write

### ISSUE THREAD

**Issue by mback2k** [VictoriaMetrics/vmctl#8]
Prometheus data written via remote_write has a specific schema documented here:
https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus/#how-prometheus-metrics-are-parsed-in-influxdb

Therefore it would be great to have a migration mode that enables to move data from InfluxDB into VictoriaMetrics which is then converted back into the original Prometheus format, e.g. no db label and no _value suffix on the timeseries.

At the end the data should look like it was directly written from Prometheus into VictoriaMetrics, just like the step over InfluxDB has never happened.

**Comment by hagen1778** [comment]
Hi @mback2k!
Hm, so such conversion could happen if influx measurement:
* has only one field
* the field is named as `value`
* there is a non-empty tag `__name__ `

Then this metric may be considered as ex-Prometheus metric written into Influx and may be recovered to original name.

Do I understand it correctly?

**Comment by mback2k** [comment]
Hi @hagen1778, yes that is correct. However I would still suggest to add a flag to enable this conversion to avoid unintended conversions for non-Prometheus data.

**Comment by ahmadalli** [comment]
so what will happen if use the current cli to import prometheus data from influxdb?

**Comment by ahmadalli** [comment]
this feature is required if we want to migrate our prometheus backend storage from influx to VM since current influx import changes the name of metrics which breaks our dashboards

**Comment by valyala** [comment]
FYI, `vmctl` has been migrated to [main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmctl). New releases for vmctl will be available at `vmutils-*.tar.gz` package on the [releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) starting from v1.53.0 . It is recommended filing new issues and feature requests for `vmctl` in [main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).

**Comment by valyala** [comment]
FYI, [vmctl](https://docs.victoriametrics.com/vmctl.html) supports `influx-prometheus-mode` command-line flag, which allows to restore the original time series written from Prometheus into InfluxDB during data migration from InfluxDB to VictoriaMetrics starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
